// Copyright 2025, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  3DGS renderer — embedded compute pipeline implementation
 *
 * Full compute pipeline: PLY loading, GPU buffer creation, 8 compute shader
 * dispatch sequence, image copy to swapchain.
 */

#include "gs_renderer.h"
#include "gs_scene_loader.h"
#include "gs_spz_loader.h"
#include <cstdio>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <string>
#include <vector>

// ── SPIR-V shader includes (generated by CMake) ─────────────────────────
#include "precomp_cov3d.comp.h"
#include "preprocess.comp.h"
#include "prefix_sum.comp.h"
#include "preprocess_sort.comp.h"
#include "hist.comp.h"
#include "sort.comp.h"
#include "tile_boundary.comp.h"
#include "render.comp.h"

// ── Uniform buffer layout (std140, matches preprocess.comp) ──────────────
struct alignas(16) GsUniformBuffer {
    float camera_position[4];  // vec4, offset 0
    float proj_mat[16];        // mat4, offset 16
    float view_mat[16];        // mat4, offset 80
    uint32_t width;            // offset 144
    uint32_t height;           // offset 148
    float tan_fovx;            // offset 152
    float tan_fovy;            // offset 156
};
static_assert(sizeof(GsUniformBuffer) == 160, "GsUniformBuffer must be 160 bytes");

// ── Helper: create a compute pipeline from SPIR-V ───────────────────────
static VkShaderModule createShaderModule(VkDevice device, const uint32_t* code, size_t sizeBytes)
{
    VkShaderModuleCreateInfo ci = {VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    ci.codeSize = sizeBytes;
    ci.pCode = code;
    VkShaderModule mod = VK_NULL_HANDLE;
    vkCreateShaderModule(device, &ci, nullptr, &mod);
    return mod;
}

static VkPipeline createComputePipeline(VkDevice device,
                                        VkPipelineLayout layout,
                                        VkShaderModule shader,
                                        const VkSpecializationInfo* specInfo = nullptr)
{
    VkComputePipelineCreateInfo ci = {VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    ci.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    ci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    ci.stage.module = shader;
    ci.stage.pName = "main";
    ci.stage.pSpecializationInfo = specInfo;
    ci.layout = layout;

    VkPipeline pipe = VK_NULL_HANDLE;
    vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &ci, nullptr, &pipe);
    return pipe;
}

// ── Helper: create descriptor set layout ─────────────────────────────────
static VkDescriptorSetLayout createDSLayout(VkDevice device,
                                            const std::vector<VkDescriptorType>& types)
{
    std::vector<VkDescriptorSetLayoutBinding> bindings(types.size());
    for (size_t i = 0; i < types.size(); i++) {
        bindings[i] = {};
        bindings[i].binding = (uint32_t)i;
        bindings[i].descriptorType = types[i];
        bindings[i].descriptorCount = 1;
        bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo ci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    ci.bindingCount = (uint32_t)bindings.size();
    ci.pBindings = bindings.data();
    VkDescriptorSetLayout layout = VK_NULL_HANDLE;
    vkCreateDescriptorSetLayout(device, &ci, nullptr, &layout);
    return layout;
}

// ── Helper: create pipeline layout ───────────────────────────────────────
static VkPipelineLayout createPipeLayout(VkDevice device,
                                         const std::vector<VkDescriptorSetLayout>& dsLayouts,
                                         uint32_t pushSize)
{
    VkPushConstantRange pcr = {};
    pcr.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    pcr.offset = 0;
    pcr.size = pushSize;

    VkPipelineLayoutCreateInfo ci = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    ci.setLayoutCount = (uint32_t)dsLayouts.size();
    ci.pSetLayouts = dsLayouts.data();
    if (pushSize > 0) {
        ci.pushConstantRangeCount = 1;
        ci.pPushConstantRanges = &pcr;
    }
    VkPipelineLayout layout = VK_NULL_HANDLE;
    vkCreatePipelineLayout(device, &ci, nullptr, &layout);
    return layout;
}

// ── Helper: allocate descriptor set ──────────────────────────────────────
static VkDescriptorSet allocDS(VkDevice device, VkDescriptorPool pool,
                               VkDescriptorSetLayout layout)
{
    VkDescriptorSetAllocateInfo ai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool = pool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &layout;
    VkDescriptorSet ds = VK_NULL_HANDLE;
    vkAllocateDescriptorSets(device, &ai, &ds);
    return ds;
}

// ── Helper: write buffer descriptor ──────────────────────────────────────
static void writeBufferDS(VkDevice device, VkDescriptorSet ds, uint32_t binding,
                          VkDescriptorType type, VkBuffer buffer, VkDeviceSize size)
{
    VkDescriptorBufferInfo bi = {};
    bi.buffer = buffer;
    bi.offset = 0;
    bi.range = size;

    VkWriteDescriptorSet w = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    w.dstSet = ds;
    w.dstBinding = binding;
    w.descriptorCount = 1;
    w.descriptorType = type;
    w.pBufferInfo = &bi;
    vkUpdateDescriptorSets(device, 1, &w, 0, nullptr);
}

// ── Helper: write image descriptor ───────────────────────────────────────
static void writeImageDS(VkDevice device, VkDescriptorSet ds, uint32_t binding,
                         VkImageView view)
{
    VkDescriptorImageInfo ii = {};
    ii.imageView = view;
    ii.imageLayout = VK_IMAGE_LAYOUT_GENERAL;

    VkWriteDescriptorSet w = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    w.dstSet = ds;
    w.dstBinding = binding;
    w.descriptorCount = 1;
    w.descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    w.pImageInfo = &ii;
    vkUpdateDescriptorSets(device, 1, &w, 0, nullptr);
}

// ═════════════════════════════════════════════════════════════════════════
// init
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::init(VkInstance instance,
                      VkPhysicalDevice physicalDevice,
                      VkDevice device,
                      VkQueue queue,
                      uint32_t queueFamilyIndex,
                      uint32_t renderWidth,
                      uint32_t renderHeight)
{
    instance_ = instance;
    physDevice_ = physicalDevice;
    device_ = device;
    queue_ = queue;
    queueFamily_ = queueFamilyIndex;
    width_ = renderWidth;
    height_ = renderHeight;

    // Query subgroup size
    VkPhysicalDeviceSubgroupProperties subgroupProps = {
        VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES};
    VkPhysicalDeviceProperties2 props2 = {VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2};
    props2.pNext = &subgroupProps;
    vkGetPhysicalDeviceProperties2(instance_ ? physDevice_ : VK_NULL_HANDLE, &props2);
    subgroupSize_ = subgroupProps.subgroupSize;
    if (subgroupSize_ == 0) subgroupSize_ = 32;

    // Tile dimensions
    tileX_ = (width_ + 15) / 16;
    tileY_ = (height_ + 15) / 16;

    // Create command pool
    VkCommandPoolCreateInfo poolInfo = {VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    poolInfo.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    poolInfo.queueFamilyIndex = queueFamilyIndex;
    VkResult res = vkCreateCommandPool(device, &poolInfo, nullptr, &cmdPool_);
    if (res != VK_SUCCESS) {
        fprintf(stderr, "GsRenderer: failed to create command pool (%d)\n", res);
        return false;
    }

    initialized_ = true;
    printf("GsRenderer: initialized (%ux%u, subgroup=%u, tiles=%ux%u)\n",
           width_, height_, subgroupSize_, tileX_, tileY_);
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// createPipelines — build all 8 compute pipelines
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::createPipelines()
{
    auto S = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    auto U = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    auto I = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;

    // 1. precomp_cov3d: set0 = {SSBO, SSBO}, push = float
    dslPrecompCov3d_ = createDSLayout(device_, {S, S});
    layoutPrecompCov3d_ = createPipeLayout(device_, {dslPrecompCov3d_}, sizeof(float));
    {
        auto mod = createShaderModule(device_, precomp_cov3d_comp_data,
                                      sizeof(precomp_cov3d_comp_data));
        pipePrecompCov3d_ = createComputePipeline(device_, layoutPrecompCov3d_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 2. preprocess: set0 = {SSBO, SSBO}, set1 = {UBO, SSBO, SSBO}
    dslPreprocessSet0_ = createDSLayout(device_, {S, S});
    dslPreprocessSet1_ = createDSLayout(device_, {U, S, S});
    layoutPreprocess_ = createPipeLayout(device_,
        {dslPreprocessSet0_, dslPreprocessSet1_}, 0);
    {
        auto mod = createShaderModule(device_, preprocess_comp_data,
                                      sizeof(preprocess_comp_data));
        pipePreprocess_ = createComputePipeline(device_, layoutPreprocess_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 3. prefix_sum: set0 = {SSBO, SSBO}, push = uint
    dslPrefixSum_ = createDSLayout(device_, {S, S});
    layoutPrefixSum_ = createPipeLayout(device_, {dslPrefixSum_}, sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, prefix_sum_comp_data,
                                      sizeof(prefix_sum_comp_data));
        pipePrefixSum_ = createComputePipeline(device_, layoutPrefixSum_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 4. preprocess_sort: set0 = {SSBO, SSBO, SSBO, SSBO}, push = uint
    dslPreprocessSort_ = createDSLayout(device_, {S, S, S, S});
    layoutPreprocessSort_ = createPipeLayout(device_, {dslPreprocessSort_}, sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, preprocess_sort_comp_data,
                                      sizeof(preprocess_sort_comp_data));
        pipePreprocessSort_ = createComputePipeline(device_, layoutPreprocessSort_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 5. hist: set0 = {SSBO, SSBO}, push = 4*uint
    dslHist_ = createDSLayout(device_, {S, S});
    layoutHist_ = createPipeLayout(device_, {dslHist_}, 4 * sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, hist_comp_data,
                                      sizeof(hist_comp_data));
        pipeHist_ = createComputePipeline(device_, layoutHist_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 6. sort: set0 = {SSBO, SSBO, SSBO, SSBO, SSBO}, push = 4*uint
    //    Specialization constant 0 = subgroupSize
    dslSort_ = createDSLayout(device_, {S, S, S, S, S});
    layoutSort_ = createPipeLayout(device_, {dslSort_}, 4 * sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, sort_comp_data,
                                      sizeof(sort_comp_data));
        VkSpecializationMapEntry specEntry = {};
        specEntry.constantID = 0;
        specEntry.offset = 0;
        specEntry.size = sizeof(uint32_t);
        VkSpecializationInfo specInfo = {};
        specInfo.mapEntryCount = 1;
        specInfo.pMapEntries = &specEntry;
        specInfo.dataSize = sizeof(uint32_t);
        specInfo.pData = &subgroupSize_;
        pipeSort_ = createComputePipeline(device_, layoutSort_, mod, &specInfo);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 7. tile_boundary: set0 = {SSBO, SSBO}, push = uint
    dslTileBoundary_ = createDSLayout(device_, {S, S});
    layoutTileBoundary_ = createPipeLayout(device_, {dslTileBoundary_}, sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, tile_boundary_comp_data,
                                      sizeof(tile_boundary_comp_data));
        pipeTileBoundary_ = createComputePipeline(device_, layoutTileBoundary_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    // 8. render: set0 = {SSBO, SSBO, SSBO}, set1 = {storage image}, push = 3*uint
    dslRenderSet0_ = createDSLayout(device_, {S, S, S});
    dslRenderSet1_ = createDSLayout(device_, {I});
    layoutRender_ = createPipeLayout(device_,
        {dslRenderSet0_, dslRenderSet1_}, 3 * sizeof(uint32_t));
    {
        auto mod = createShaderModule(device_, render_comp_data,
                                      sizeof(render_comp_data));
        pipeRender_ = createComputePipeline(device_, layoutRender_, mod);
        vkDestroyShaderModule(device_, mod, nullptr);
    }

    printf("GsRenderer: 8 compute pipelines created\n");
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// createBuffers — allocate all GPU buffers
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::createBuffers()
{
    uint32_t N = numGaussians_;
    uint32_t totalTiles = tileX_ * tileY_;
    maxSortInstances_ = N * 4;
    // Ensure capacity for a single splat covering all tiles
    if (maxSortInstances_ < totalTiles)
        maxSortInstances_ = totalTiles;

    auto devLocal = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
    auto hostVis = (VkMemoryPropertyFlags)(VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                           VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    auto ssboUsage = (VkBufferUsageFlags)(VK_BUFFER_USAGE_STORAGE_BUFFER_BIT |
                                          VK_BUFFER_USAGE_TRANSFER_DST_BIT |
                                          VK_BUFFER_USAGE_TRANSFER_SRC_BIT);

    // Vertex data (uploaded via staging)
    vertexBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 240, ssboUsage, devLocal);

    // Cov3D (written by precomp_cov3d)
    cov3DBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 24, ssboUsage, devLocal);

    // Uniform buffer (host-visible, mapped each frame)
    uniformBuffer_ = gsCreateBuffer(device_, physDevice_,
        sizeof(GsUniformBuffer),
        VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
        hostVis);

    // Vertex attributes (written by preprocess, read by preprocess_sort + render)
    vertexAttrBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 64, ssboUsage, devLocal);

    // Tile overlap counts (written by preprocess, copied to prefix ping)
    tileOverlapBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 4, ssboUsage, devLocal);

    // Prefix sum ping/pong buffers
    prefixSumPingBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 4, ssboUsage, devLocal);
    prefixSumPongBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)N * 4, ssboUsage, devLocal);

    // Total sum readback (host-visible)
    totalSumHostBuffer_ = gsCreateBuffer(device_, physDevice_,
        sizeof(uint32_t),
        VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        hostVis);

    // Sort key/value buffers (4x capacity)
    sortKeysEvenBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)maxSortInstances_ * 8, ssboUsage, devLocal);
    sortKeysOddBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)maxSortInstances_ * 8, ssboUsage, devLocal);
    sortValsEvenBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)maxSortInstances_ * 4, ssboUsage, devLocal);
    sortValsOddBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)maxSortInstances_ * 4, ssboUsage, devLocal);

    // Sort histogram
    // numWorkgroups for radix sort:
    uint32_t globalInv = (maxSortInstances_ + numRadixSortBlocksPerWG_ * 256 - 1) /
                         (numRadixSortBlocksPerWG_ * 256);
    numSortWorkgroups_ = globalInv;
    if (numSortWorkgroups_ == 0) numSortWorkgroups_ = 1;
    sortHistBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)numSortWorkgroups_ * 256 * 4, ssboUsage, devLocal);

    // Tile boundary
    tileBoundaryBuffer_ = gsCreateBuffer(device_, physDevice_,
        (VkDeviceSize)tileX_ * tileY_ * 2 * 4, ssboUsage, devLocal);

    // Internal render image
    renderImage_ = gsCreateImage2D(device_, physDevice_, width_, height_,
        VK_FORMAT_R8G8B8A8_UNORM,
        VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT);

    printf("GsRenderer: buffers allocated (N=%u, sortCap=%u, hist_wg=%u)\n",
           N, maxSortInstances_, numSortWorkgroups_);
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// createDescriptorSets
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::createDescriptorSets()
{
    // Descriptor pool — count all needed descriptors
    VkDescriptorPoolSize poolSizes[] = {
        {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 40},
        {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 2},
        {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 2},
    };
    VkDescriptorPoolCreateInfo pci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    pci.maxSets = 16;
    pci.poolSizeCount = 3;
    pci.pPoolSizes = poolSizes;
    if (vkCreateDescriptorPool(device_, &pci, nullptr, &descriptorPool_) != VK_SUCCESS) {
        fprintf(stderr, "GsRenderer: failed to create descriptor pool\n");
        return false;
    }

    uint32_t N = numGaussians_;

    // 1. precomp_cov3d set0: vertices + cov3d
    dsPrecompCov3d_ = allocDS(device_, descriptorPool_, dslPrecompCov3d_);
    writeBufferDS(device_, dsPrecompCov3d_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  vertexBuffer_.buffer, vertexBuffer_.size);
    writeBufferDS(device_, dsPrecompCov3d_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  cov3DBuffer_.buffer, cov3DBuffer_.size);

    // 2. preprocess set0: vertices + cov3d (same data as precomp)
    dsPreprocessSet0_ = allocDS(device_, descriptorPool_, dslPreprocessSet0_);
    writeBufferDS(device_, dsPreprocessSet0_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  vertexBuffer_.buffer, vertexBuffer_.size);
    writeBufferDS(device_, dsPreprocessSet0_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  cov3DBuffer_.buffer, cov3DBuffer_.size);

    // 3. preprocess set1: uniform + vertexAttrs + tileOverlap
    dsPreprocessSet1_ = allocDS(device_, descriptorPool_, dslPreprocessSet1_);
    writeBufferDS(device_, dsPreprocessSet1_, 0, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
                  uniformBuffer_.buffer, uniformBuffer_.size);
    writeBufferDS(device_, dsPreprocessSet1_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  vertexAttrBuffer_.buffer, vertexAttrBuffer_.size);
    writeBufferDS(device_, dsPreprocessSet1_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  tileOverlapBuffer_.buffer, tileOverlapBuffer_.size);

    // 4. prefix_sum set0: ping + pong
    dsPrefixSum_ = allocDS(device_, descriptorPool_, dslPrefixSum_);
    writeBufferDS(device_, dsPrefixSum_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  prefixSumPingBuffer_.buffer, prefixSumPingBuffer_.size);
    writeBufferDS(device_, dsPrefixSum_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  prefixSumPongBuffer_.buffer, prefixSumPongBuffer_.size);

    // 5. preprocess_sort set0: vertexAttrs + prefixResult + keysEven + valsEven
    //    The prefix sum result location depends on iteration parity.
    //    We bind the correct buffer here based on numPrefixSumIter_.
    dsPreprocessSort_ = allocDS(device_, descriptorPool_, dslPreprocessSort_);
    writeBufferDS(device_, dsPreprocessSort_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  vertexAttrBuffer_.buffer, vertexAttrBuffer_.size);
    {
        // Result is in pong if numPrefixSumIter_ is odd, ping if even
        VkBuffer prefixResult = (numPrefixSumIter_ % 2 == 1) ?
            prefixSumPongBuffer_.buffer : prefixSumPingBuffer_.buffer;
        VkDeviceSize prefixSize = (VkDeviceSize)N * 4;
        writeBufferDS(device_, dsPreprocessSort_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                      prefixResult, prefixSize);
    }
    writeBufferDS(device_, dsPreprocessSort_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysEvenBuffer_.buffer, sortKeysEvenBuffer_.size);
    writeBufferDS(device_, dsPreprocessSort_, 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsEvenBuffer_.buffer, sortValsEvenBuffer_.size);

    // 6. hist — two descriptor sets for even/odd sort passes
    dsHistEven_ = allocDS(device_, descriptorPool_, dslHist_);
    writeBufferDS(device_, dsHistEven_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysEvenBuffer_.buffer, sortKeysEvenBuffer_.size);
    writeBufferDS(device_, dsHistEven_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortHistBuffer_.buffer, sortHistBuffer_.size);

    dsHistOdd_ = allocDS(device_, descriptorPool_, dslHist_);
    writeBufferDS(device_, dsHistOdd_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysOddBuffer_.buffer, sortKeysOddBuffer_.size);
    writeBufferDS(device_, dsHistOdd_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortHistBuffer_.buffer, sortHistBuffer_.size);

    // 7. sort — two descriptor sets for even→odd and odd→even
    dsSortEvenToOdd_ = allocDS(device_, descriptorPool_, dslSort_);
    writeBufferDS(device_, dsSortEvenToOdd_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysEvenBuffer_.buffer, sortKeysEvenBuffer_.size);
    writeBufferDS(device_, dsSortEvenToOdd_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysOddBuffer_.buffer, sortKeysOddBuffer_.size);
    writeBufferDS(device_, dsSortEvenToOdd_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsEvenBuffer_.buffer, sortValsEvenBuffer_.size);
    writeBufferDS(device_, dsSortEvenToOdd_, 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsOddBuffer_.buffer, sortValsOddBuffer_.size);
    writeBufferDS(device_, dsSortEvenToOdd_, 4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortHistBuffer_.buffer, sortHistBuffer_.size);

    dsSortOddToEven_ = allocDS(device_, descriptorPool_, dslSort_);
    writeBufferDS(device_, dsSortOddToEven_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysOddBuffer_.buffer, sortKeysOddBuffer_.size);
    writeBufferDS(device_, dsSortOddToEven_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysEvenBuffer_.buffer, sortKeysEvenBuffer_.size);
    writeBufferDS(device_, dsSortOddToEven_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsOddBuffer_.buffer, sortValsOddBuffer_.size);
    writeBufferDS(device_, dsSortOddToEven_, 3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsEvenBuffer_.buffer, sortValsEvenBuffer_.size);
    writeBufferDS(device_, dsSortOddToEven_, 4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortHistBuffer_.buffer, sortHistBuffer_.size);

    // 8. tile_boundary: sortedKeysEven + boundaries
    dsTileBoundary_ = allocDS(device_, descriptorPool_, dslTileBoundary_);
    writeBufferDS(device_, dsTileBoundary_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortKeysEvenBuffer_.buffer, sortKeysEvenBuffer_.size);
    writeBufferDS(device_, dsTileBoundary_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  tileBoundaryBuffer_.buffer, tileBoundaryBuffer_.size);

    // 9. render set0: vertexAttrs + boundaries + sortedValsEven
    dsRenderSet0_ = allocDS(device_, descriptorPool_, dslRenderSet0_);
    writeBufferDS(device_, dsRenderSet0_, 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  vertexAttrBuffer_.buffer, vertexAttrBuffer_.size);
    writeBufferDS(device_, dsRenderSet0_, 1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  tileBoundaryBuffer_.buffer, tileBoundaryBuffer_.size);
    writeBufferDS(device_, dsRenderSet0_, 2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                  sortValsEvenBuffer_.buffer, sortValsEvenBuffer_.size);

    // 10. render set1: output image
    dsRenderSet1_ = allocDS(device_, descriptorPool_, dslRenderSet1_);
    writeImageDS(device_, dsRenderSet1_, 0, renderImage_.view);

    printf("GsRenderer: descriptor sets created\n");
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// dispatchPrecompCov3d — one-time 3D covariance precomputation
// ═════════════════════════════════════════════════════════════════════════

void GsRenderer::dispatchPrecompCov3d()
{
    VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    ai.commandPool = cmdPool_;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VkCommandBuffer cmd;
    vkAllocateCommandBuffers(device_, &ai, &cmd);

    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipePrecompCov3d_);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
        layoutPrecompCov3d_, 0, 1, &dsPrecompCov3d_, 0, nullptr);

    float scaleFactor = 1.0f;
    vkCmdPushConstants(cmd, layoutPrecompCov3d_, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(float), &scaleFactor);

    uint32_t groups = (numGaussians_ + 255) / 256;
    vkCmdDispatch(cmd, groups, 1, 1);

    vkEndCommandBuffer(cmd);

    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);

    printf("GsRenderer: precomp_cov3d dispatched (%u groups)\n", groups);
}

// ═════════════════════════════════════════════════════════════════════════
// loadScene
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::loadScene(const char* plyPath)
{
    if (!initialized_) {
        fprintf(stderr, "GsRenderer: not initialized\n");
        return false;
    }

    // Clean up previous scene if any
    cleanupScene();

    // Auto-detect format by extension and parse scene file
    std::vector<GsVertex> vertices;
    std::string scenePath(plyPath);
    std::string ext = scenePath.substr(scenePath.find_last_of('.'));
    std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);

    bool parseOk;
    if (ext == ".spz") {
        parseOk = ParseSpzFile(scenePath, vertices);
    } else {
        parseOk = ParsePlyFile(scenePath, vertices);
    }

    if (!parseOk || vertices.empty()) {
        fprintf(stderr, "GsRenderer: failed to parse scene file: %s\n", plyPath);
        return false;
    }

    numGaussians_ = (uint32_t)vertices.size();
    numPrefixSumIter_ = (uint32_t)std::ceil(std::log2((double)numGaussians_));
    if (numPrefixSumIter_ == 0) numPrefixSumIter_ = 1;

    // Build compact pick data for CPU raycast (20 bytes/gaussian)
    pickData_.resize(numGaussians_);
    for (uint32_t i = 0; i < numGaussians_; i++) {
        const auto& v = vertices[i];
        pickData_[i].px = v.position[0];
        pickData_[i].py = v.position[1];
        pickData_[i].pz = v.position[2];
        pickData_[i].maxScale = std::max({v.scale_opacity[0], v.scale_opacity[1], v.scale_opacity[2]});
        pickData_[i].opacity = v.scale_opacity[3];
    }

    // Create compute pipelines (first time only — they don't depend on scene size)
    if (pipePrecompCov3d_ == VK_NULL_HANDLE) {
        if (!createPipelines()) {
            fprintf(stderr, "GsRenderer: failed to create pipelines\n");
            return false;
        }
    }

    // Create GPU buffers
    if (!createBuffers()) {
        fprintf(stderr, "GsRenderer: failed to create buffers\n");
        return false;
    }

    // Upload vertex data via staging buffer
    if (!gsUploadBuffer(device_, physDevice_, queue_, cmdPool_,
                        vertexBuffer_, vertices.data(),
                        (VkDeviceSize)vertices.size() * sizeof(GsVertex))) {
        fprintf(stderr, "GsRenderer: failed to upload vertex data\n");
        return false;
    }

    // Create descriptor sets (must be after buffer creation)
    if (!createDescriptorSets()) {
        fprintf(stderr, "GsRenderer: failed to create descriptor sets\n");
        return false;
    }

    // One-time: transition render image to GENERAL layout
    {
        VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        ai.commandPool = cmdPool_;
        ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = 1;
        VkCommandBuffer cmd;
        vkAllocateCommandBuffers(device_, &ai, &cmd);
        VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &bi);

        VkImageMemoryBarrier imb = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        imb.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        imb.newLayout = VK_IMAGE_LAYOUT_GENERAL;
        imb.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.image = renderImage_.image;
        imb.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
        imb.srcAccessMask = 0;
        imb.dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1, &imb);

        vkEndCommandBuffer(cmd);
        VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
        si.commandBufferCount = 1;
        si.pCommandBuffers = &cmd;
        vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
        vkQueueWaitIdle(queue_);
        vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    }

    // Dispatch one-time precomp_cov3d
    dispatchPrecompCov3d();

    loadedScenePath_ = plyPath;
    sceneLoaded_ = true;

    printf("GsRenderer: scene loaded: %s (%u gaussians)\n", plyPath, numGaussians_);
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// loadDebugScene — single synthetic splat for pipeline debugging
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::loadDebugScene(float x, float y, float z, float radius)
{
    if (!initialized_) {
        fprintf(stderr, "GsRenderer: not initialized\n");
        return false;
    }
    cleanupScene();

    // Build a single GsVertex (240 bytes)
    GsVertex v = {};
    v.position[0] = x;
    v.position[1] = y;
    v.position[2] = z;
    v.position[3] = 1.0f;

    // Scale = radius (already exp'd), opacity = 0.99 (already sigmoid'd)
    v.scale_opacity[0] = radius;
    v.scale_opacity[1] = radius;
    v.scale_opacity[2] = radius;
    v.scale_opacity[3] = 0.99f;

    // Identity quaternion (w,x,y,z)
    v.rotation[0] = 1.0f;
    v.rotation[1] = 0.0f;
    v.rotation[2] = 0.0f;
    v.rotation[3] = 0.0f;

    // SH DC for red: color = SH_C0 * dc + 0.5
    // SH_C0 = 0.28209479177387814
    // red=(1,0,0): dc_r = 0.5/0.28209 ≈ 1.7725, dc_g = dc_b = -1.7725
    float dc_r =  0.5f / 0.28209479f;
    float dc_g = -0.5f / 0.28209479f;
    float dc_b = -0.5f / 0.28209479f;
    v.sh[0] = dc_r;   // R dc
    v.sh[1] = dc_g;   // G dc
    v.sh[2] = dc_b;   // B dc
    // All other SH coefficients remain 0

    std::vector<GsVertex> vertices = {v};
    numGaussians_ = 1;
    numPrefixSumIter_ = 1;

    // Build pick data for the single debug splat
    pickData_.resize(1);
    pickData_[0] = {x, y, z, radius, 0.99f};

    if (pipePrecompCov3d_ == VK_NULL_HANDLE) {
        if (!createPipelines()) return false;
    }
    if (!createBuffers()) return false;
    if (!gsUploadBuffer(device_, physDevice_, queue_, cmdPool_,
                        vertexBuffer_, vertices.data(),
                        (VkDeviceSize)sizeof(GsVertex))) {
        return false;
    }
    if (!createDescriptorSets()) return false;

    // Transition render image to GENERAL
    {
        VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        ai.commandPool = cmdPool_;
        ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = 1;
        VkCommandBuffer cmd;
        vkAllocateCommandBuffers(device_, &ai, &cmd);
        VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &bi);
        VkImageMemoryBarrier imb = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        imb.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        imb.newLayout = VK_IMAGE_LAYOUT_GENERAL;
        imb.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.image = renderImage_.image;
        imb.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
        imb.srcAccessMask = 0;
        imb.dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1, &imb);
        vkEndCommandBuffer(cmd);
        VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
        si.commandBufferCount = 1;
        si.pCommandBuffers = &cmd;
        vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
        vkQueueWaitIdle(queue_);
        vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    }

    dispatchPrecompCov3d();

    loadedScenePath_ = "<debug: 1 red splat>";
    sceneLoaded_ = true;

    printf("GsRenderer: debug scene loaded — 1 red splat at (%.2f, %.2f, %.2f) radius=%.3f\n",
           x, y, z, radius);
    return true;
}

bool GsRenderer::hasScene() const { return sceneLoaded_; }
const std::string& GsRenderer::scenePath() const { return loadedScenePath_; }
uint32_t GsRenderer::gaussianCount() const { return numGaussians_; }

// ═════════════════════════════════════════════════════════════════════════
// updateUniforms — write view/proj matrices to the mapped uniform buffer
// ═════════════════════════════════════════════════════════════════════════

void GsRenderer::updateUniforms(const float viewMatrix[16], const float projMatrix[16],
                                uint32_t vpWidth, uint32_t vpHeight)
{
    GsUniformBuffer ub;

    // Extract camera position from view matrix: cam = -R^T * t
    // Column-major: col0=[0..3], col1=[4..7], col2=[8..11], col3=[12..15]
    float tx = viewMatrix[12], ty = viewMatrix[13], tz = viewMatrix[14];
    ub.camera_position[0] = -(viewMatrix[0]*tx + viewMatrix[1]*ty + viewMatrix[2]*tz);
    ub.camera_position[1] = -(viewMatrix[4]*tx + viewMatrix[5]*ty + viewMatrix[6]*tz);
    ub.camera_position[2] = -(viewMatrix[8]*tx + viewMatrix[9]*ty + viewMatrix[10]*tz);
    ub.camera_position[3] = 1.0f;

    // proj_mat = projMatrix * viewMatrix (combined view-projection)
    // The shader does: p_hom = proj_mat * worldPos → clip space
    for (int col = 0; col < 4; col++) {
        for (int row = 0; row < 4; row++) {
            float sum = 0.0f;
            for (int k = 0; k < 4; k++) {
                sum += projMatrix[k * 4 + row] * viewMatrix[col * 4 + k];
            }
            ub.proj_mat[col * 4 + row] = sum;
        }
    }

    // view_mat = viewMatrix with Z row negated (make positive Z = forward)
    // This is needed because the shader's Jacobian and near-plane test assume
    // positive Z for objects in front of the camera.
    // OpenXR uses -Z forward; we negate row 2 so p_view.z becomes positive.
    memcpy(ub.view_mat, viewMatrix, 16 * sizeof(float));
    // Negate row 2 (column-major indices 2, 6, 10, 14)
    ub.view_mat[2]  = -ub.view_mat[2];
    ub.view_mat[6]  = -ub.view_mat[6];
    ub.view_mat[10] = -ub.view_mat[10];
    ub.view_mat[14] = -ub.view_mat[14];

    ub.width = vpWidth;
    ub.height = vpHeight;

    // Extract tan_fov from projection matrix
    // For a perspective projection: proj[0][0] ≈ 1/tan_fovx, proj[1][1] ≈ 1/tan_fovy
    float p00 = projMatrix[0];   // [0][0] in column-major
    float p11 = projMatrix[5];   // [1][1] in column-major
    ub.tan_fovx = (std::abs(p00) > 1e-6f) ? (1.0f / std::abs(p00)) : 1.0f;
    ub.tan_fovy = (std::abs(p11) > 1e-6f) ? (1.0f / std::abs(p11)) : 1.0f;

    // Map and write
    void* mapped = nullptr;
    vkMapMemory(device_, uniformBuffer_.memory, 0, sizeof(GsUniformBuffer), 0, &mapped);
    memcpy(mapped, &ub, sizeof(GsUniformBuffer));
    vkUnmapMemory(device_, uniformBuffer_.memory);
}

// ═════════════════════════════════════════════════════════════════════════
// renderEye — full per-frame compute dispatch sequence
// ═════════════════════════════════════════════════════════════════════════

void GsRenderer::renderEye(VkImage swapchainImage,
                           VkFormat swapchainFormat,
                           uint32_t imageWidth,
                           uint32_t imageHeight,
                           uint32_t viewportX,
                           uint32_t viewportY,
                           uint32_t viewportWidth,
                           uint32_t viewportHeight,
                           const float viewMatrix[16],
                           const float projMatrix[16])
{
    if (!hasScene()) return;

    // Update uniform buffer with this eye's matrices
    updateUniforms(viewMatrix, projMatrix, viewportWidth, viewportHeight);

    uint32_t N = numGaussians_;
    uint32_t groups256 = (N + 255) / 256;

    // ── CMD 1: preprocess + prefix_sum + copy totalSum ───────────────────
    {
        VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        ai.commandPool = cmdPool_;
        ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = 1;
        VkCommandBuffer cmd;
        vkAllocateCommandBuffers(device_, &ai, &cmd);
        VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &bi);

        // Preprocess dispatch
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipePreprocess_);
        VkDescriptorSet ppSets[] = {dsPreprocessSet0_, dsPreprocessSet1_};
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
            layoutPreprocess_, 0, 2, ppSets, 0, nullptr);
        vkCmdDispatch(cmd, groups256, 1, 1);

        // Barrier: preprocess writes → prefix sum reads
        VkMemoryBarrier mb = {VK_STRUCTURE_TYPE_MEMORY_BARRIER};
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_TRANSFER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_TRANSFER_BIT,
            0, 1, &mb, 0, nullptr, 0, nullptr);

        // Copy tileOverlap → prefixPing (initial data for prefix sum)
        VkBufferCopy copyRegion = {};
        copyRegion.size = (VkDeviceSize)N * 4;
        vkCmdCopyBuffer(cmd, tileOverlapBuffer_.buffer,
                        prefixSumPingBuffer_.buffer, 1, &copyRegion);

        // Barrier: copy → prefix sum
        mb.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        // Prefix sum: log2(N) iterations
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipePrefixSum_);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
            layoutPrefixSum_, 0, 1, &dsPrefixSum_, 0, nullptr);

        for (uint32_t t = 0; t < numPrefixSumIter_; t++) {
            vkCmdPushConstants(cmd, layoutPrefixSum_, VK_SHADER_STAGE_COMPUTE_BIT,
                               0, sizeof(uint32_t), &t);
            vkCmdDispatch(cmd, groups256, 1, 1);

            // Barrier between prefix sum iterations
            mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
            mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);
        }

        // Copy last element of prefix sum result → totalSumHost
        // Result is in pong if numPrefixSumIter_ is odd, ping if even
        VkBuffer prefixResult = (numPrefixSumIter_ % 2 == 1) ?
            prefixSumPongBuffer_.buffer : prefixSumPingBuffer_.buffer;

        // Barrier: prefix sum → transfer
        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        VkBufferCopy totalCopy = {};
        totalCopy.srcOffset = (VkDeviceSize)(N - 1) * 4;
        totalCopy.size = 4;
        vkCmdCopyBuffer(cmd, prefixResult, totalSumHostBuffer_.buffer, 1, &totalCopy);

        vkEndCommandBuffer(cmd);
        VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
        si.commandBufferCount = 1;
        si.pCommandBuffers = &cmd;
        vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
        vkQueueWaitIdle(queue_);
        vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    }

    // ── CPU readback: read totalSum ──────────────────────────────────────
    uint32_t numInstances = 0;
    {
        void* mapped = nullptr;
        vkMapMemory(device_, totalSumHostBuffer_.memory, 0, sizeof(uint32_t), 0, &mapped);
        memcpy(&numInstances, mapped, sizeof(uint32_t));
        vkUnmapMemory(device_, totalSumHostBuffer_.memory);
    }

    // Clamp to sort buffer capacity
    if (numInstances > maxSortInstances_) {
        numInstances = maxSortInstances_;
    }

    if (numInstances == 0) {
        // No visible gaussians — skip sort and render, just clear
        return;
    }

    // ── CMD 2: sort + render + copy to swapchain ─────────────────────────
    {
        VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
        ai.commandPool = cmdPool_;
        ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        ai.commandBufferCount = 1;
        VkCommandBuffer cmd;
        vkAllocateCommandBuffers(device_, &ai, &cmd);
        VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(cmd, &bi);

        VkMemoryBarrier mb = {VK_STRUCTURE_TYPE_MEMORY_BARRIER};

        // ─── preprocess_sort ─────────────────────────────────────────
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipePreprocessSort_);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
            layoutPreprocessSort_, 0, 1, &dsPreprocessSort_, 0, nullptr);
        uint32_t vpTileX = (viewportWidth + 15) / 16;
        vkCmdPushConstants(cmd, layoutPreprocessSort_, VK_SHADER_STAGE_COMPUTE_BIT,
                           0, sizeof(uint32_t), &vpTileX);
        vkCmdDispatch(cmd, groups256, 1, 1);

        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        // ─── Radix sort: 8 passes (64-bit keys, 8 bits per pass) ────
        struct RadixSortPC {
            uint32_t num_elements;
            uint32_t shift;
            uint32_t num_workgroups;
            uint32_t num_blocks_per_workgroup;
        };

        for (uint32_t pass = 0; pass < 8; pass++) {
            bool even = (pass % 2 == 0);

            RadixSortPC pc;
            pc.num_elements = numInstances;
            pc.shift = pass * 8;
            pc.num_workgroups = numSortWorkgroups_;
            pc.num_blocks_per_workgroup = numRadixSortBlocksPerWG_;

            // Histogram pass
            vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeHist_);
            VkDescriptorSet histDS = even ? dsHistEven_ : dsHistOdd_;
            vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                layoutHist_, 0, 1, &histDS, 0, nullptr);
            vkCmdPushConstants(cmd, layoutHist_, VK_SHADER_STAGE_COMPUTE_BIT,
                               0, sizeof(RadixSortPC), &pc);
            vkCmdDispatch(cmd, numSortWorkgroups_, 1, 1);

            mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
            mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

            // Sort/scatter pass
            vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeSort_);
            VkDescriptorSet sortDS = even ? dsSortEvenToOdd_ : dsSortOddToEven_;
            vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                layoutSort_, 0, 1, &sortDS, 0, nullptr);
            vkCmdPushConstants(cmd, layoutSort_, VK_SHADER_STAGE_COMPUTE_BIT,
                               0, sizeof(RadixSortPC), &pc);
            vkCmdDispatch(cmd, numSortWorkgroups_, 1, 1);

            mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
            mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
            vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);
        }
        // After 8 passes (even number), sorted result is back in even buffers

        // ─── Fill tileBoundary with zeros ────────────────────────────
        vkCmdFillBuffer(cmd, tileBoundaryBuffer_.buffer, 0,
                        tileBoundaryBuffer_.size, 0);

        mb.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        // ─── Tile boundary ───────────────────────────────────────────
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeTileBoundary_);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
            layoutTileBoundary_, 0, 1, &dsTileBoundary_, 0, nullptr);
        vkCmdPushConstants(cmd, layoutTileBoundary_, VK_SHADER_STAGE_COMPUTE_BIT,
                           0, sizeof(uint32_t), &numInstances);
        uint32_t tbGroups = (numInstances + 255) / 256;
        vkCmdDispatch(cmd, tbGroups, 1, 1);

        mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &mb, 0, nullptr, 0, nullptr);

        // ─── Render ──────────────────────────────────────────────────
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeRender_);
        VkDescriptorSet renderSets[] = {dsRenderSet0_, dsRenderSet1_};
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
            layoutRender_, 0, 2, renderSets, 0, nullptr);

        // Never apply manual sRGB encoding — the swapchain is SRGB format,
        // so the compositor's sampler decodes sRGB→linear on read, and the
        // display surface re-encodes linear→sRGB on output (single gamma).
        // Manual linearToSrgb() would cause double encoding (washed out colors).
        uint32_t renderPC[3] = {viewportWidth, viewportHeight, 0u};
        vkCmdPushConstants(cmd, layoutRender_, VK_SHADER_STAGE_COMPUTE_BIT,
                           0, sizeof(renderPC), renderPC);

        uint32_t renderGroupsX = (viewportWidth + 15) / 16;
        uint32_t renderGroupsY = (viewportHeight + 15) / 16;
        vkCmdDispatch(cmd, renderGroupsX, renderGroupsY, 1);

        // ─── Copy render image → swapchain viewport region ──────────

        // Barrier: render image GENERAL → TRANSFER_SRC
        VkImageMemoryBarrier imb = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        imb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        imb.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        imb.oldLayout = VK_IMAGE_LAYOUT_GENERAL;
        imb.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        imb.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb.image = renderImage_.image;
        imb.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
            VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &imb);

        // Barrier: swapchain image → TRANSFER_DST
        // First eye (vpX==0): UNDEFINED is fine (fresh acquire, ok to discard).
        // Second eye in SBS: must use COLOR_ATTACHMENT_OPTIMAL to preserve first eye.
        VkImageMemoryBarrier imb2 = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        imb2.srcAccessMask = (viewportX == 0) ? (VkAccessFlags)0 : VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        imb2.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        imb2.oldLayout = (viewportX == 0) ? VK_IMAGE_LAYOUT_UNDEFINED
                                          : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        imb2.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
        imb2.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb2.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        imb2.image = swapchainImage;
        imb2.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
            VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, nullptr, 0, nullptr, 1, &imb2);

        // Copy viewport region
        VkImageCopy region = {};
        region.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        region.srcOffset = {0, 0, 0};
        region.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        region.dstOffset = {(int32_t)viewportX, (int32_t)viewportY, 0};
        region.extent = {viewportWidth, viewportHeight, 1};
        vkCmdCopyImage(cmd,
            renderImage_.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
            swapchainImage, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            1, &region);

        // Barrier: swapchain image → COLOR_ATTACHMENT_OPTIMAL
        imb2.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        imb2.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
        imb2.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
        imb2.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
            VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
            0, 0, nullptr, 0, nullptr, 1, &imb2);

        // Barrier: render image back to GENERAL for next use
        imb.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        imb.dstAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
        imb.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        imb.newLayout = VK_IMAGE_LAYOUT_GENERAL;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
            VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1, &imb);

        vkEndCommandBuffer(cmd);
        VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
        si.commandBufferCount = 1;
        si.pCommandBuffers = &cmd;
        vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
        vkQueueWaitIdle(queue_);
        vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    }
}

// ═════════════════════════════════════════════════════════════════════════
// pickGaussian — CPU raycast to find nearest visible gaussian along a ray
// ═════════════════════════════════════════════════════════════════════════

bool GsRenderer::pickGaussian(const float rayOrigin[3], const float rayDir[3],
                               float hitPos[3], float maxDistance) const
{
    if (pickData_.empty()) return false;

    float bestScore = 1e30f;
    int bestIdx = -1;

    for (size_t i = 0; i < pickData_.size(); i++) {
        const auto& g = pickData_[i];

        // Vector from ray origin to gaussian center
        float dx = g.px - rayOrigin[0];
        float dy = g.py - rayOrigin[1];
        float dz = g.pz - rayOrigin[2];

        // Project center onto ray: t = dot(d, rayDir)
        float t = dx * rayDir[0] + dy * rayDir[1] + dz * rayDir[2];

        // Reject if behind camera or beyond max distance
        if (t < 0.0f || t > maxDistance) continue;

        // Perpendicular distance squared from ray to center
        float perpX = dx - t * rayDir[0];
        float perpY = dy - t * rayDir[1];
        float perpZ = dz - t * rayDir[2];
        float perpDistSq = perpX * perpX + perpY * perpY + perpZ * perpZ;

        // Reject if ray misses the 3-sigma sphere
        float radius = 3.0f * g.maxScale;
        if (perpDistSq > radius * radius) continue;

        // Score: favor close, opaque, large gaussians
        float perpDist = sqrtf(perpDistSq);
        float eps = 1e-6f;
        float score = (perpDist + eps) / (g.opacity * g.maxScale + eps);

        if (score < bestScore) {
            bestScore = score;
            bestIdx = (int)i;
        }
    }

    if (bestIdx < 0) return false;

    hitPos[0] = pickData_[bestIdx].px;
    hitPos[1] = pickData_[bestIdx].py;
    hitPos[2] = pickData_[bestIdx].pz;
    return true;
}

// ═════════════════════════════════════════════════════════════════════════
// cleanupScene — destroy scene-specific resources (buffers, descriptors)
// ═════════════════════════════════════════════════════════════════════════

void GsRenderer::cleanupScene()
{
    if (!device_) return;
    vkDeviceWaitIdle(device_);

    // Destroy descriptor pool (frees all allocated sets)
    if (descriptorPool_ != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(device_, descriptorPool_, nullptr);
        descriptorPool_ = VK_NULL_HANDLE;
    }

    // Reset all descriptor set handles
    dsPrecompCov3d_ = VK_NULL_HANDLE;
    dsPreprocessSet0_ = VK_NULL_HANDLE;
    dsPreprocessSet1_ = VK_NULL_HANDLE;
    dsPrefixSum_ = VK_NULL_HANDLE;
    dsPreprocessSort_ = VK_NULL_HANDLE;
    dsHistEven_ = VK_NULL_HANDLE;
    dsHistOdd_ = VK_NULL_HANDLE;
    dsSortEvenToOdd_ = VK_NULL_HANDLE;
    dsSortOddToEven_ = VK_NULL_HANDLE;
    dsTileBoundary_ = VK_NULL_HANDLE;
    dsRenderSet0_ = VK_NULL_HANDLE;
    dsRenderSet1_ = VK_NULL_HANDLE;

    // Destroy buffers
    gsDestroyBuffer(device_, vertexBuffer_);
    gsDestroyBuffer(device_, cov3DBuffer_);
    gsDestroyBuffer(device_, uniformBuffer_);
    gsDestroyBuffer(device_, vertexAttrBuffer_);
    gsDestroyBuffer(device_, tileOverlapBuffer_);
    gsDestroyBuffer(device_, prefixSumPingBuffer_);
    gsDestroyBuffer(device_, prefixSumPongBuffer_);
    gsDestroyBuffer(device_, totalSumHostBuffer_);
    gsDestroyBuffer(device_, sortKeysEvenBuffer_);
    gsDestroyBuffer(device_, sortKeysOddBuffer_);
    gsDestroyBuffer(device_, sortValsEvenBuffer_);
    gsDestroyBuffer(device_, sortValsOddBuffer_);
    gsDestroyBuffer(device_, sortHistBuffer_);
    gsDestroyBuffer(device_, tileBoundaryBuffer_);

    // Destroy render image
    gsDestroyImage(device_, renderImage_);

    pickData_.clear();
    pickData_.shrink_to_fit();

    sceneLoaded_ = false;
    numGaussians_ = 0;
}

// ═════════════════════════════════════════════════════════════════════════
// cleanup — destroy all resources
// ═════════════════════════════════════════════════════════════════════════

void GsRenderer::cleanup()
{
    if (!device_) return;
    vkDeviceWaitIdle(device_);

    cleanupScene();

    // Destroy pipelines
    auto dp = [&](VkPipeline& p) { if (p) { vkDestroyPipeline(device_, p, nullptr); p = VK_NULL_HANDLE; } };
    dp(pipePrecompCov3d_);
    dp(pipePreprocess_);
    dp(pipePrefixSum_);
    dp(pipePreprocessSort_);
    dp(pipeHist_);
    dp(pipeSort_);
    dp(pipeTileBoundary_);
    dp(pipeRender_);

    // Destroy pipeline layouts
    auto dl = [&](VkPipelineLayout& l) { if (l) { vkDestroyPipelineLayout(device_, l, nullptr); l = VK_NULL_HANDLE; } };
    dl(layoutPrecompCov3d_);
    dl(layoutPreprocess_);
    dl(layoutPrefixSum_);
    dl(layoutPreprocessSort_);
    dl(layoutHist_);
    dl(layoutSort_);
    dl(layoutTileBoundary_);
    dl(layoutRender_);

    // Destroy descriptor set layouts
    auto dd = [&](VkDescriptorSetLayout& d) { if (d) { vkDestroyDescriptorSetLayout(device_, d, nullptr); d = VK_NULL_HANDLE; } };
    dd(dslPrecompCov3d_);
    dd(dslPreprocessSet0_);
    dd(dslPreprocessSet1_);
    dd(dslPrefixSum_);
    dd(dslPreprocessSort_);
    dd(dslHist_);
    dd(dslSort_);
    dd(dslTileBoundary_);
    dd(dslRenderSet0_);
    dd(dslRenderSet1_);

    // Destroy command pool
    if (cmdPool_ != VK_NULL_HANDLE) {
        vkDestroyCommandPool(device_, cmdPool_, nullptr);
        cmdPool_ = VK_NULL_HANDLE;
    }

    device_ = VK_NULL_HANDLE;  // Prevent double-cleanup from destructor
    initialized_ = false;
}

GsRenderer::~GsRenderer()
{
    cleanup();
}
