// Copyright 2025, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
// Ported from VkRadixSort by Mirco Werner (https://github.com/MircoWerner/VkRadixSort)
// via 3DGS.cpp. Radix sort histogram pass.

#version 460
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

#define WORKGROUP_SIZE 256
#define RADIX_SORT_BINS 256U
#define BITS 64
#define key_t uint64_t

layout (local_size_x = WORKGROUP_SIZE) in;

layout (push_constant, std430) uniform PushConstants {
    uint g_num_elements;
    uint g_shift;
    uint g_num_workgroups;
    uint g_num_blocks_per_workgroup;
};

layout (std430, set = 0, binding = 0) buffer elements_in {
    key_t g_elements_in[];
};

layout (std430, set = 0, binding = 1) buffer histograms {
    uint g_histograms[];
};

shared uint[RADIX_SORT_BINS] histogram;

void main() {
    uint lID = gl_LocalInvocationID.x;
    uint wID = gl_WorkGroupID.x;

    if (lID < RADIX_SORT_BINS) {
        histogram[lID] = 0U;
    }
    barrier();

    for (uint index = 0; index < g_num_blocks_per_workgroup; index++) {
        uint elementId = wID * g_num_blocks_per_workgroup * WORKGROUP_SIZE + index * WORKGROUP_SIZE + lID;
        if (elementId < g_num_elements) {
            const uint bin = uint(g_elements_in[elementId] >> g_shift) & (RADIX_SORT_BINS - 1);
            atomicAdd(histogram[bin], 1U);
        }
    }
    barrier();

    if (lID < RADIX_SORT_BINS) {
        g_histograms[RADIX_SORT_BINS * wID + lID] = histogram[lID];
    }
}
