// Copyright 2025, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
// Ported from 3DGS.cpp (https://github.com/shg8/3DGS.cpp)
// Generate sort keys (tileIdx<<32 | depth) from prefix sum offsets.

#version 450
#extension GL_GOOGLE_include_directive : enable
#include "common.glsl"

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

layout (std430, set = 0, binding = 0) readonly buffer Vertices {
    VertexAttribute attr[];
};

layout (std430, set = 0, binding = 1) readonly buffer In {
    uint prefixSum[];
};

layout (std430, set = 0, binding = 2) writeonly buffer OutKeys {
    uint64_t keys[];
};

layout (std430, set = 0, binding = 3) writeonly buffer OutPayloads {
    uint payloads[];
};

layout (push_constant) uniform Constants {
    uint tileX;
};

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= prefixSum.length()) {
        return;
    }

    if (attr[index].color_radii.w == 0) {
        return;
    }

    uint ind = index == 0 ? 0 : prefixSum[index - 1];

    for (uint i = attr[index].aabb.x; i < attr[index].aabb.z; i++) {
        for (uint j = attr[index].aabb.y; j < attr[index].aabb.w; j++) {
            uint64_t tileIndex = i + j * tileX;
            uint depthBits = floatBitsToUint(attr[index].depth);
            uint64_t k = (tileIndex << 32) | uint64_t(depthBits);
            keys[ind] = k;
            payloads[ind] = index;
            ind++;
        }
    }
}
